[global]
input_files = ["input.ron"]

[rust]
extra_mounts = { "rust/.rustfmt.toml" = "/app/.rustfmt.toml" }
[[rust.task]]
template = "templates/rust/component_type_summary.rs.jinja"
output_dir = "rust/src/models"
[[rust.task]]
template = "templates/rust/component_type.rs.jinja"
output_dir = "rust/src/models"
