name: ACP Rust Release

on:
  push:
    branches:
      - "mendy/acp-release"

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    if: contains(github.event.head_commit.message, '[release]')
    runs-on: ubuntu-24.04
    environment: release

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish --manifest-path rust/Cargo.toml
