name: ACP Python Release

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - "mendy/acp-release"

jobs:
  release:
    if: contains(github.event.head_commit.message, '[release]')
    name: Build distributions
    runs-on: ubuntu-24.04
    environment: release

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        name: Install Python
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          cd python
          python -m pip install --upgrade pip
          python -m pip install .

      - name: Install build
        run: |
          cd python
          python -m pip install build

      - name: Build distributions
        run: |
          cd python
          python -m build

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TWINE_ACP_PACKAGE_PASSWORD }}
          packages_dir: python/dist
